// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzBYFJu897n6AZYYdwyZNPO-RstkIOfU',
    appId: '1:75065498625:web:9c1f8c0f6fb4e91d947400',
    messagingSenderId: '75065498625',
    projectId: 'dress-app-f256c',
    authDomain: 'dress-app-f256c.firebaseapp.com',
    storageBucket: 'dress-app-f256c.firebasestorage.app',
    measurementId: 'G-FYTG0B8NFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3Vu5cgWOroFaLQ30RJIciHq00zQIQys',
    appId: '1:75065498625:android:ced86919c728e615947400',
    messagingSenderId: '75065498625',
    projectId: 'dress-app-f256c',
    storageBucket: 'dress-app-f256c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdYMdYFH7arTXM0rXDh207LJHBU8HcH7w',
    appId: '1:75065498625:ios:f077fcddf65e499d947400',
    messagingSenderId: '75065498625',
    projectId: 'dress-app-f256c',
    storageBucket: 'dress-app-f256c.firebasestorage.app',
    iosClientId: '75065498625-b4n7cg7sm6aj952fmhd5eucjonn2pk6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.dressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyzBYFJu897n6AZYYdwyZNPO-RstkIOfU',
    appId: '1:75065498625:web:5da6bc50ce1b9b16947400',
    messagingSenderId: '75065498625',
    projectId: 'dress-app-f256c',
    authDomain: 'dress-app-f256c.firebaseapp.com',
    storageBucket: 'dress-app-f256c.firebasestorage.app',
    measurementId: 'G-0G6W595LBS',
  );
}
